### ISSUE TITLE
Cannot overwrite existing folder

### ISSUE THREAD

**Issue by pepelsbey** [shower/cli#14]
Steps to reproduce:

1. `shower create semantics`
2. Wait…
3. `shower create semantics`
4. Do you want to overwrite it? Yes

```
~/Documents/Пепелсбей.net/Сайт/pres
$ shower create semantics
? The semantics dir already exists. Do you want to overwrite it? Yes
shower create [<directory>]

- Create a new project

Positionals:
  directory

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
    at safeCheck (/Users/pepelsbey/.nvm/versions/node/v10.10.0/lib/node_modules/shower-cli/node_modules/del/index.js:18:9)
    at mapper (/Users/pepelsbey/.nvm/versions/node/v10.10.0/lib/node_modules/shower-cli/node_modules/del/index.js:33:4)
    at Promise.resolve.then.el (/Users/pepelsbey/.nvm/versions/node/v10.10.0/lib/node_modules/shower-cli/node_modules/p-map/index.js:46:16)
```

**Comment by nikolay-govorov** [comment]
Hmm, I can not repoduce it. Which version do you use?

**Comment by pepelsbey** [comment]
- shower 0.2.2
- node v10.10.0
- npm 6.4.1

**Comment by nikolay-govorov** [comment]
And operating system?

**Comment by pepelsbey** [comment]
macOS Mojave, 10.14

**Comment by nikolay-govorov** [comment]
Hey @pepelsbey. Do you still face this problem on the latest version?

**Comment by pepelsbey** [comment]
Tried both Y and N options, it works as expected now. Thank you!
