### ISSUE TITLE
File not found error in 0.2.3

### ISSUE THREAD

**Issue by pepelsbey** [shower/cli#19]
Steps to reproduce:

```
shower create
cd slides
shower prepare
```

Output:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: /Users/pepelsbey/Desktop/slides/node_modules/shower-lib/shower.min.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:273:13)
    at Glob.emit (events.js:182:13)
    at Glob._finish (/Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/glob/glob.js:197:8)
    at done (/Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/glob/glob.js:688:12)
    at /Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/glob/glob.js:764:12)
    at RES (/Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/inflight/inflight.js:31:16)
Emitted 'error' event at:
    at Pumpify.emit (events.js:182:13)
    at Pumpify.Duplexify._destroy (/Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/duplexify/index.js:191:15)
    at /Users/pepelsbey/.nvm/versions/node/v10.11.0/lib/node_modules/shower-cli/node_modules/duplexify/index.js:182:10
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Maybe we should have some tests that would run and check basic functions before allowing project to be published to npm? Otherwise it breaks too often and it’s hard to rely on such tool :(

When I publish theme updates with np utility, it runs tests first. It allows updates to be published to npm only if they pass.

**Comment by nikolay-govorov** [comment]
You're right, it shouldn't be. Today I urgently released 0.2.4 where I fixed this behavior, fixed another problem with `archive`. I manually checked that everything works correctly.

The problem is that I do not yet know how to effectively and automatically test the CLI interface. We now have a number of automated tests for the PDF task. I think for the release of `0.3.0` I will pay special attention to the reliability of the code and implement CI for automatic publication of the package

**Comment by pepelsbey** [comment]
Thank you for quickly fixing a releasing it. I just wanted to share this tool with Shower users and promote it as the best workflow for creating and editing presentation. But before I do it I need to make sure that it’s stable and convenient enough to use. I’ve been using it to create my presentation (basically, testing in a real situation) recently and this is where all the issues and requests are coming from.

Let’s then wait until 0.3.0 release before starting promoting it. I was thinking about screencast, just like [the one](https://youtu.be/l2OelK_hIro) I did a while ago.
