### ISSUE TITLE
evalCalcExpression is not defined

### ISSUE THREAD

**Issue by pepelsbey** [shower/cli#8]
```
$ shower pdf
☐  pending   Creating PDF in progress
Error: Evaluation failed: ReferenceError: evalCalcExpression is not defined
    at Promise (__puppeteer_evaluation_script__:6:7)
    at new Promise (<anonymous>)
    at __puppeteer_evaluation_script__:1:8
    at ExecutionContext.evaluateHandle (/Users/pepelsbey/.nvm/versions/node/v10.9.0/lib/node_modules/shower-cli/node_modules/puppeteer/lib/ExecutionContext.js:98:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
✔  success   PDF built in 'presentation.pdf' [in 2s]
…
$ shower --version
0.1.3
```

**Comment by nikolay-govorov** [comment]
@pepelsbey, thank! I fixed it. To prevent this from happening again, I implemented basic regression testing
